workflows:
  ios-app-store:
    name: iOS App Store
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - shiprate
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.shiprate.app
    triggering:
      events: []
    scripts:
      - name: Decode GoogleService-Info.plist
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
      - name: Install dependencies
        script: flutter pub get
      - name: Generate launcher icons
        script: dart run flutter_launcher_icons
      - name: Generate native splash
        script: dart run flutter_native_splash:create
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build IPA
        script: flutter build ipa --release --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: true