workflows:
  ios-app-store:
    name: iOS App Store
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        GOOGLE_SERVICE_INFO_PLIST: $GOOGLE_SERVICE_INFO_PLIST
        CM_CERTIFICATE: $CM_CERTIFICATE
        CM_CERTIFICATE_PASSWORD: $CM_CERTIFICATE_PASSWORD
        CM_PROVISIONING_PROFILE: $CM_PROVISIONING_PROFILE
        APP_STORE_CONNECT_ISSUER_ID: 8ec86ef2-ceda-4dbb-87f2-0f3d4d39eaff
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
      ios_signing:
        certificate: $CM_CERTIFICATE
        certificate_password: $CM_CERTIFICATE_PASSWORD
        provisioning_profiles:
          - profile: $CM_PROVISIONING_PROFILE
    triggering:
      events: []
    scripts:
      - name: Decode GoogleService-Info.plist
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
      - name: Generate launcher icons
        script: dart run flutter_launcher_icons
      - name: Generate native splash
        script: dart run flutter_native_splash:create
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        issuer_id: 8ec86ef2-ceda-4dbb-87f2-0f3d4d39eaff
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_app_store: true
