// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFFFbTHNPMA9t1ABrC_uk92ym8SEKSSHI',
    appId: '1:718297005782:web:1a2e4f254323a13c685377',
    messagingSenderId: '718297005782',
    projectId: 'shiprate-daf18',
    authDomain: 'shiprate-daf18.firebaseapp.com',
    storageBucket: 'shiprate-daf18.firebasestorage.app',
    measurementId: 'G-ZP68WL1MM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbAJpwGPew2p-mbp80NxOYTr6jhTuN6TY',
    appId: '1:718297005782:android:5d50892d8fd13901685377',
    messagingSenderId: '718297005782',
    projectId: 'shiprate-daf18',
    storageBucket: 'shiprate-daf18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1EejUoI6xnVlN1NKqH2fxeqj74P0QzgI',
    appId: '1:718297005782:ios:fe6012043accec24685377',
    messagingSenderId: '718297005782',
    projectId: 'shiprate-daf18',
    storageBucket: 'shiprate-daf18.firebasestorage.app',
    iosBundleId: 'com.example.shipRate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1EejUoI6xnVlN1NKqH2fxeqj74P0QzgI',
    appId: '1:718297005782:ios:fe6012043accec24685377',
    messagingSenderId: '718297005782',
    projectId: 'shiprate-daf18',
    storageBucket: 'shiprate-daf18.firebasestorage.app',
    iosBundleId: 'com.example.shipRate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFFFbTHNPMA9t1ABrC_uk92ym8SEKSSHI',
    appId: '1:718297005782:web:9b2f16339448b652685377',
    messagingSenderId: '718297005782',
    projectId: 'shiprate-daf18',
    authDomain: 'shiprate-daf18.firebaseapp.com',
    storageBucket: 'shiprate-daf18.firebasestorage.app',
    measurementId: 'G-4X0MHXE477',
  );
}
