import 'package:flutter_test/flutter_test.dart';
import 'package:ship_rate/data/services/monthly_report_service.dart';
import 'package:ship_rate/features/subscription/monthly_report_pdf.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('generates a populated monthly report PDF', () async {
    final labels = MonthlyReportPdfLabels(
      monthTitle: 'Outubro 2026',
      contributionReport: 'Relatório de contribuições',
      yourRankings: 'Suas posições',
      noContributions: 'Nenhuma contribuição registrada neste mês',
      autoGenerated: 'Relatório gerado automaticamente',
      ratingsOfMonth: 'Avaliações do mês',
      depthsRecorded: 'Profundidades registradas',
      crossingsReported: 'Cruzamentos registrados',
      ratings: 'Avaliações',
      depths: 'Profundidades',
      crossings: 'Cruzamentos',
      shipColumn: 'Navio',
      dateColumn: 'Data',
      averageColumn: 'Média',
      locationColumn: 'Local',
      totalDepthColumn: 'Profundidade total',
      generatedOn: (date) => 'Gerado em $date',
      ofTotalPilots: (total) => 'de $total práticos',
    );
    final data = MonthlyReportData(
      month: DateTime(2026, 10),
      pilotName: 'MASSAO',
      pilotEmail: 'pilot@example.com',
      subscriptionPlan: 'plus',
      ratings: [
        MonthlyRating(
          shipName: 'Maya Bay',
          date: DateTime(2026, 10, 2),
          averageScore: 4.8,
        ),
      ],
      depthRecords: [
        MonthlyDepthRecord(
          locationName: 'Peixe Boi',
          date: DateTime(2026, 10, 3),
          totalDepth: 15.6,
        ),
      ],
      crossings: [
        MonthlyCrossing(
          shipName: 'Amazon Star',
          locationName: 'Ponta do Céu',
          date: DateTime(2026, 10, 4),
          direction: 'subindo',
        ),
      ],
      ratingRanking: 3,
      depthRanking: 4,
      crossingRanking: 5,
      totalPilots: 109,
    );

    final bytes = await MonthlyReportPdf(labels).generatePdf(data);

    expect(bytes.length, greaterThan(2000));
    expect(String.fromCharCodes(bytes.take(4)), '%PDF');
  });
}
